using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;

namespace Thumper_Mod_Loader
{
    public class LevelRecord
    {
        [JsonProperty(Order = 1)]
        public string Info = "This file is used to locally store your highest score for a level and is used whenever you have this level in the mod loader. If you delete this file, your local record/completion of this level will be zero.";
        [JsonProperty(Order = 2)]
        public string Name { get; set; }
        [JsonProperty(Order = 3)]
        public string Rank
        {
            get => _rank;
            set {
                if (value == "RANK_NONE")
                    value = "RANK_C";
                _rank = value;
            }
        }
        private string _rank { get; set; }
        [JsonProperty(Order = 4)]
        public string RankPlus
        {
            get => _rankplus;
            set {
                if (value == "RANK_NONE")
                    value = "RANK_C";
                _rankplus = value;
            }
        }
        private string _rankplus { get; set; }
        [JsonProperty(Order = 5)]
        public int? Score { get; set; } = 0;
        [JsonProperty(Order = 6)]
        public int? ScorePlus { get; set; } = 0;
        [JsonProperty(Order = 7)]
        public string IntegrityHash { get; set; }
        [JsonProperty(Order = 8)]
        public string Warning = "Do not edit this file. The integrity hash is used to verify this file has not been edited. If the mod loader detects changes, this record will be removed and reset to 0.";

        public static byte[] GetHash(string inputString)
        {
            using (HashAlgorithm algorithm = SHA256.Create())
                return algorithm.ComputeHash(Encoding.UTF8.GetBytes(inputString));
        }

        public static string GetHashString(string inputString)
        {
            StringBuilder sb = new StringBuilder();
            foreach (byte b in GetHash(inputString))
                sb.Append(b.ToString("X2"));

            return sb.ToString();
        }

        public string GetIntegrityHash()
        {
            return GetHashString($"{Name}{Rank}{RankPlus}{Score}{ScorePlus}{86}{new Random(Properties.Resources.d6.GetPixel(32, 32).R).Next()}");
        }

        public void ResetRecord()
        {
            this.Rank = "RANK_C";
            this.RankPlus = "RANK_C";
            this.Score = 0;
            this.ScorePlus = 0;
            this.IntegrityHash = GetIntegrityHash();
        }
    }
}
